{{- if .Values.agentCollector.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-agent
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "opentelemetry-collector.selectorLabels" . | nindent 6 }}
      component: agent-collector
  updateStrategy:
    {{- if not (eq .Values.agentCollector.updateStrategy "OnDelete") }}
    rollingUpdate:
      {{- if .Values.agentCollector.rollingUpdate.maxSurge }}
      maxSurge: {{ .Values.agentCollector.rollingUpdate.maxSurge }}
      {{- end }}
      {{- if .Values.agentCollector.rollingUpdate.maxUnavailable }}
      maxUnavailable: {{ .Values.agentCollector.rollingUpdate.maxUnavailable }}
      {{- else }}
      maxUnavailable: 1
      {{- end }}
    {{- end }}
    type: {{ .Values.agentCollector.updateStrategy }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-agent.yaml") . | sha256sum }}
        {{- with .Values.agentCollector.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "opentelemetry-collector.selectorLabels" . | nindent 8 }}
        component: agent-collector
        {{- with .Values.agentCollector.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- $podValues := deepCopy .Values.agentCollector | mustMergeOverwrite (deepCopy .Values) }}
      {{- $podData := dict "Values" $podValues "configmapSuffix" "-agent" "isAgent" true }}
      {{- include "opentelemetry-collector.pod" ($podData | mustMergeOverwrite (deepCopy .)) | nindent 6 }}
      hostNetwork: {{ .Values.agentCollector.hostNetwork }}
{{- end }}
